project='lua-box'
title='lua box documentation'
description='A util to setup multiple sandboxes'
format='discount'
backtick_references=false
file='../box.lua'
dir='../out'
-- readme='doc.md'
style='!pale'
kind_names={topic='Manual',script='Programs'}
--[[
examples = {
    '../tests/styles/colon.lua',
    '../tests/styles/four.lua',
    '../tests/styles/three.lua',
    '../tests/styles/multiple.lua',
    '../tests/example/mylib.c',
    '../tests/moonscript/List.moon',
}
]]--
